name: OneList Auto Restart

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: 10 22 * * *

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install IBM CLI
      run: curl -sL https://raw.githubusercontent.com/IBM-Bluemix/developer-tools-installer/master/linux-installer/idt-installer | bash
      
    - name: Login IBM Cloud
      run: |
        ibmcloud login -u ${{ secrets.OneList_MAIL }} -p ${{ secrets.OneList_PWD }} -r ${{ secrets.OneList_RGN }}
    - name: Restart
      run: |
        ibmcloud target -g Default
        ibmcloud target --cf
        ibmcloud cf install
        ibmcloud cf restart ${{ secrets.OneList_CFNAME }}
