name: OneList Auto Restart

on:
  push:
    branches: master
  watch:
    types: started
  schedule:
    - cron: 10 22 * * *

jobs:
  IBM-Cloud-CF-APP-Restart:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install CF CLI
      run: |
        curl -L "https://packages.cloudfoundry.org/stable?release=linux64-binary&source=github&version=v6" | tar -zx
        sudo mv cf /usr/local/bin
      
    - name: Login CF
      run: cf l -a https://api.${{ secrets.OneList_RGN }}.cf.cloud.ibm.com login -u ${{ secrets.OneList_MAIL }} -p ${{ secrets.OneManager_PWD }}
      
    - name: Restart CF APP
      run: cf rs ${{ secrets.OneList_CFNAME }}
